# Generated by Django 2.0.4 on 2018-04-21 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CartApp', '0002_auto_20180421_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7),
        ),
    ]
