# Generated by Django 2.0.4 on 2018-04-21 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookBarnApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='bookFormat',
            field=models.CharField(blank=True, help_text='eg. Paperback, Hardcover', max_length=50, null=True, verbose_name='Book Format'),
        ),
    ]
